version: '3.8'

services:
  codesec-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8008:5173"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run preview -- --port 5173 --host
